Use GESTION_LINEAS_COLECTIVOS;

GO

ALTER TABLE SERVICIO
ADD CONSTRAINT FK_Servicio_Linea
FOREIGN KEY (IdLinea) REFERENCES LINEA(IdLinea);
GO

ALTER TABLE SERVICIO
ADD CONSTRAINT FK_Servicio_Unidad
FOREIGN KEY (IdUnidad) REFERENCES UNIDAD(IdUnidad);
GO

ALTER TABLE SERVICIO
ADD CONSTRAINT FK_Servicio_Chofer
FOREIGN KEY (IdChofer) REFERENCES CHOFER(IdChofer);
GO

ALTER TABLE UNIDAD
ADD CONSTRAINT FK_Unidad_Linea
FOREIGN KEY (IdLinea) REFERENCES LINEA(IdLinea);
GO

ALTER TABLE CHOFER
ADD CONSTRAINT FK_Chofer_Linea
FOREIGN KEY (IdLinea) REFERENCES LINEA(IdLinea);
GO

ALTER TABLE PARADA
ADD CONSTRAINT FK_Parada_Linea
FOREIGN KEY (IdLinea) REFERENCES LINEA(IdLinea);
GO

ALTER TABLE RECORRIDO
ADD CONSTRAINT FK_Recorrido_Linea
FOREIGN KEY (IdLinea) REFERENCES LINEA(IdLinea);
GO

ALTER TABLE RECORRIDO_PARADA
ADD CONSTRAINT FK_RecorridoParada_Recorrido
FOREIGN KEY (IdRecorrido) REFERENCES RECORRIDO(IdRecorrido);
GO

ALTER TABLE RECORRIDO_PARADA
ADD CONSTRAINT FK_RecorridoParada_Parada
FOREIGN KEY (IdParada) REFERENCES PARADA(IdParada);
GO



